version: ">= 0.15.0"

formatter: markdown

header-from: readme-header.md
footer-from: ""

sections:
  hide: []
  show: []
  

  hide-all: false
  show-all: true

content: |-
  {{ .Header }}

  {{ .Requirements }}

  ## Examples

  ### Example A

  ```hcl
  {{ include "examples/exampleA/main.tf" }}
  ```

  ### Example B

  ```hcl
  {{ include "examples/exampleB/main.tf" }}
  ```

  {{ .Providers }}
  
  {{ .Modules }}

  {{ .Inputs }}
  
  {{ .Outputs }}
  
  {{ .Resources }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true